CREATE TABLE events
(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
event_date DATE NOT NULL,
event_type VARCHAR(24) NOT NULL,
event_summary VARCHAR(1024) NOT NULL,
event_size INT NOT NULL,
event_detail CLOB NOT NULL,
CONSTRAINT primary_key PRIMARY KEY (id)
)